/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VanChuyenRouteImport } from './routes/van-chuyen'
import { Route as SanPhamRouteImport } from './routes/san-pham'
import { Route as NhaCungCapRouteImport } from './routes/nha-cung-cap'
import { Route as MuaHangRouteImport } from './routes/mua-hang'
import { Route as LoaiChiPhiRouteImport } from './routes/loai-chi-phi'
import { Route as KhoHoaDonRouteImport } from './routes/kho-hoa-don'
import { Route as KhachHangRouteImport } from './routes/khach-hang'
import { Route as HoaDonRouteImport } from './routes/hoa-don'
import { Route as HdDauVaoRouteImport } from './routes/hd-dau-vao'
import { Route as HdDauRaRouteImport } from './routes/hd-dau-ra'
import { Route as DonViVcRouteImport } from './routes/don-vi-vc'
import { Route as CongNoVcRouteImport } from './routes/cong-no-vc'
import { Route as CongNoNccRouteImport } from './routes/cong-no-ncc'
import { Route as CongNoKhRouteImport } from './routes/cong-no-kh'
import { Route as CongNoRouteImport } from './routes/cong-no'
import { Route as ChiPhiRouteImport } from './routes/chi-phi'
import { Route as BaoCaoRouteImport } from './routes/bao-cao'
import { Route as BanHangRouteImport } from './routes/ban-hang'
import { Route as IndexRouteImport } from './routes/index'

const VanChuyenRoute = VanChuyenRouteImport.update({
  id: '/van-chuyen',
  path: '/van-chuyen',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamRoute = SanPhamRouteImport.update({
  id: '/san-pham',
  path: '/san-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const NhaCungCapRoute = NhaCungCapRouteImport.update({
  id: '/nha-cung-cap',
  path: '/nha-cung-cap',
  getParentRoute: () => rootRouteImport,
} as any)
const MuaHangRoute = MuaHangRouteImport.update({
  id: '/mua-hang',
  path: '/mua-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const LoaiChiPhiRoute = LoaiChiPhiRouteImport.update({
  id: '/loai-chi-phi',
  path: '/loai-chi-phi',
  getParentRoute: () => rootRouteImport,
} as any)
const KhoHoaDonRoute = KhoHoaDonRouteImport.update({
  id: '/kho-hoa-don',
  path: '/kho-hoa-don',
  getParentRoute: () => rootRouteImport,
} as any)
const KhachHangRoute = KhachHangRouteImport.update({
  id: '/khach-hang',
  path: '/khach-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const HoaDonRoute = HoaDonRouteImport.update({
  id: '/hoa-don',
  path: '/hoa-don',
  getParentRoute: () => rootRouteImport,
} as any)
const HdDauVaoRoute = HdDauVaoRouteImport.update({
  id: '/hd-dau-vao',
  path: '/hd-dau-vao',
  getParentRoute: () => rootRouteImport,
} as any)
const HdDauRaRoute = HdDauRaRouteImport.update({
  id: '/hd-dau-ra',
  path: '/hd-dau-ra',
  getParentRoute: () => rootRouteImport,
} as any)
const DonViVcRoute = DonViVcRouteImport.update({
  id: '/don-vi-vc',
  path: '/don-vi-vc',
  getParentRoute: () => rootRouteImport,
} as any)
const CongNoVcRoute = CongNoVcRouteImport.update({
  id: '/cong-no-vc',
  path: '/cong-no-vc',
  getParentRoute: () => rootRouteImport,
} as any)
const CongNoNccRoute = CongNoNccRouteImport.update({
  id: '/cong-no-ncc',
  path: '/cong-no-ncc',
  getParentRoute: () => rootRouteImport,
} as any)
const CongNoKhRoute = CongNoKhRouteImport.update({
  id: '/cong-no-kh',
  path: '/cong-no-kh',
  getParentRoute: () => rootRouteImport,
} as any)
const CongNoRoute = CongNoRouteImport.update({
  id: '/cong-no',
  path: '/cong-no',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiPhiRoute = ChiPhiRouteImport.update({
  id: '/chi-phi',
  path: '/chi-phi',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoCaoRoute = BaoCaoRouteImport.update({
  id: '/bao-cao',
  path: '/bao-cao',
  getParentRoute: () => rootRouteImport,
} as any)
const BanHangRoute = BanHangRouteImport.update({
  id: '/ban-hang',
  path: '/ban-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ban-hang': typeof BanHangRoute
  '/bao-cao': typeof BaoCaoRoute
  '/chi-phi': typeof ChiPhiRoute
  '/cong-no': typeof CongNoRoute
  '/cong-no-kh': typeof CongNoKhRoute
  '/cong-no-ncc': typeof CongNoNccRoute
  '/cong-no-vc': typeof CongNoVcRoute
  '/don-vi-vc': typeof DonViVcRoute
  '/hd-dau-ra': typeof HdDauRaRoute
  '/hd-dau-vao': typeof HdDauVaoRoute
  '/hoa-don': typeof HoaDonRoute
  '/khach-hang': typeof KhachHangRoute
  '/kho-hoa-don': typeof KhoHoaDonRoute
  '/loai-chi-phi': typeof LoaiChiPhiRoute
  '/mua-hang': typeof MuaHangRoute
  '/nha-cung-cap': typeof NhaCungCapRoute
  '/san-pham': typeof SanPhamRoute
  '/van-chuyen': typeof VanChuyenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ban-hang': typeof BanHangRoute
  '/bao-cao': typeof BaoCaoRoute
  '/chi-phi': typeof ChiPhiRoute
  '/cong-no': typeof CongNoRoute
  '/cong-no-kh': typeof CongNoKhRoute
  '/cong-no-ncc': typeof CongNoNccRoute
  '/cong-no-vc': typeof CongNoVcRoute
  '/don-vi-vc': typeof DonViVcRoute
  '/hd-dau-ra': typeof HdDauRaRoute
  '/hd-dau-vao': typeof HdDauVaoRoute
  '/hoa-don': typeof HoaDonRoute
  '/khach-hang': typeof KhachHangRoute
  '/kho-hoa-don': typeof KhoHoaDonRoute
  '/loai-chi-phi': typeof LoaiChiPhiRoute
  '/mua-hang': typeof MuaHangRoute
  '/nha-cung-cap': typeof NhaCungCapRoute
  '/san-pham': typeof SanPhamRoute
  '/van-chuyen': typeof VanChuyenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ban-hang': typeof BanHangRoute
  '/bao-cao': typeof BaoCaoRoute
  '/chi-phi': typeof ChiPhiRoute
  '/cong-no': typeof CongNoRoute
  '/cong-no-kh': typeof CongNoKhRoute
  '/cong-no-ncc': typeof CongNoNccRoute
  '/cong-no-vc': typeof CongNoVcRoute
  '/don-vi-vc': typeof DonViVcRoute
  '/hd-dau-ra': typeof HdDauRaRoute
  '/hd-dau-vao': typeof HdDauVaoRoute
  '/hoa-don': typeof HoaDonRoute
  '/khach-hang': typeof KhachHangRoute
  '/kho-hoa-don': typeof KhoHoaDonRoute
  '/loai-chi-phi': typeof LoaiChiPhiRoute
  '/mua-hang': typeof MuaHangRoute
  '/nha-cung-cap': typeof NhaCungCapRoute
  '/san-pham': typeof SanPhamRoute
  '/van-chuyen': typeof VanChuyenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ban-hang'
    | '/bao-cao'
    | '/chi-phi'
    | '/cong-no'
    | '/cong-no-kh'
    | '/cong-no-ncc'
    | '/cong-no-vc'
    | '/don-vi-vc'
    | '/hd-dau-ra'
    | '/hd-dau-vao'
    | '/hoa-don'
    | '/khach-hang'
    | '/kho-hoa-don'
    | '/loai-chi-phi'
    | '/mua-hang'
    | '/nha-cung-cap'
    | '/san-pham'
    | '/van-chuyen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ban-hang'
    | '/bao-cao'
    | '/chi-phi'
    | '/cong-no'
    | '/cong-no-kh'
    | '/cong-no-ncc'
    | '/cong-no-vc'
    | '/don-vi-vc'
    | '/hd-dau-ra'
    | '/hd-dau-vao'
    | '/hoa-don'
    | '/khach-hang'
    | '/kho-hoa-don'
    | '/loai-chi-phi'
    | '/mua-hang'
    | '/nha-cung-cap'
    | '/san-pham'
    | '/van-chuyen'
  id:
    | '__root__'
    | '/'
    | '/ban-hang'
    | '/bao-cao'
    | '/chi-phi'
    | '/cong-no'
    | '/cong-no-kh'
    | '/cong-no-ncc'
    | '/cong-no-vc'
    | '/don-vi-vc'
    | '/hd-dau-ra'
    | '/hd-dau-vao'
    | '/hoa-don'
    | '/khach-hang'
    | '/kho-hoa-don'
    | '/loai-chi-phi'
    | '/mua-hang'
    | '/nha-cung-cap'
    | '/san-pham'
    | '/van-chuyen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BanHangRoute: typeof BanHangRoute
  BaoCaoRoute: typeof BaoCaoRoute
  ChiPhiRoute: typeof ChiPhiRoute
  CongNoRoute: typeof CongNoRoute
  CongNoKhRoute: typeof CongNoKhRoute
  CongNoNccRoute: typeof CongNoNccRoute
  CongNoVcRoute: typeof CongNoVcRoute
  DonViVcRoute: typeof DonViVcRoute
  HdDauRaRoute: typeof HdDauRaRoute
  HdDauVaoRoute: typeof HdDauVaoRoute
  HoaDonRoute: typeof HoaDonRoute
  KhachHangRoute: typeof KhachHangRoute
  KhoHoaDonRoute: typeof KhoHoaDonRoute
  LoaiChiPhiRoute: typeof LoaiChiPhiRoute
  MuaHangRoute: typeof MuaHangRoute
  NhaCungCapRoute: typeof NhaCungCapRoute
  SanPhamRoute: typeof SanPhamRoute
  VanChuyenRoute: typeof VanChuyenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/van-chuyen': {
      id: '/van-chuyen'
      path: '/van-chuyen'
      fullPath: '/van-chuyen'
      preLoaderRoute: typeof VanChuyenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham': {
      id: '/san-pham'
      path: '/san-pham'
      fullPath: '/san-pham'
      preLoaderRoute: typeof SanPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nha-cung-cap': {
      id: '/nha-cung-cap'
      path: '/nha-cung-cap'
      fullPath: '/nha-cung-cap'
      preLoaderRoute: typeof NhaCungCapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mua-hang': {
      id: '/mua-hang'
      path: '/mua-hang'
      fullPath: '/mua-hang'
      preLoaderRoute: typeof MuaHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loai-chi-phi': {
      id: '/loai-chi-phi'
      path: '/loai-chi-phi'
      fullPath: '/loai-chi-phi'
      preLoaderRoute: typeof LoaiChiPhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kho-hoa-don': {
      id: '/kho-hoa-don'
      path: '/kho-hoa-don'
      fullPath: '/kho-hoa-don'
      preLoaderRoute: typeof KhoHoaDonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khach-hang': {
      id: '/khach-hang'
      path: '/khach-hang'
      fullPath: '/khach-hang'
      preLoaderRoute: typeof KhachHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoa-don': {
      id: '/hoa-don'
      path: '/hoa-don'
      fullPath: '/hoa-don'
      preLoaderRoute: typeof HoaDonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hd-dau-vao': {
      id: '/hd-dau-vao'
      path: '/hd-dau-vao'
      fullPath: '/hd-dau-vao'
      preLoaderRoute: typeof HdDauVaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hd-dau-ra': {
      id: '/hd-dau-ra'
      path: '/hd-dau-ra'
      fullPath: '/hd-dau-ra'
      preLoaderRoute: typeof HdDauRaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don-vi-vc': {
      id: '/don-vi-vc'
      path: '/don-vi-vc'
      fullPath: '/don-vi-vc'
      preLoaderRoute: typeof DonViVcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-no-vc': {
      id: '/cong-no-vc'
      path: '/cong-no-vc'
      fullPath: '/cong-no-vc'
      preLoaderRoute: typeof CongNoVcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-no-ncc': {
      id: '/cong-no-ncc'
      path: '/cong-no-ncc'
      fullPath: '/cong-no-ncc'
      preLoaderRoute: typeof CongNoNccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-no-kh': {
      id: '/cong-no-kh'
      path: '/cong-no-kh'
      fullPath: '/cong-no-kh'
      preLoaderRoute: typeof CongNoKhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-no': {
      id: '/cong-no'
      path: '/cong-no'
      fullPath: '/cong-no'
      preLoaderRoute: typeof CongNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-phi': {
      id: '/chi-phi'
      path: '/chi-phi'
      fullPath: '/chi-phi'
      preLoaderRoute: typeof ChiPhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-cao': {
      id: '/bao-cao'
      path: '/bao-cao'
      fullPath: '/bao-cao'
      preLoaderRoute: typeof BaoCaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ban-hang': {
      id: '/ban-hang'
      path: '/ban-hang'
      fullPath: '/ban-hang'
      preLoaderRoute: typeof BanHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BanHangRoute: BanHangRoute,
  BaoCaoRoute: BaoCaoRoute,
  ChiPhiRoute: ChiPhiRoute,
  CongNoRoute: CongNoRoute,
  CongNoKhRoute: CongNoKhRoute,
  CongNoNccRoute: CongNoNccRoute,
  CongNoVcRoute: CongNoVcRoute,
  DonViVcRoute: DonViVcRoute,
  HdDauRaRoute: HdDauRaRoute,
  HdDauVaoRoute: HdDauVaoRoute,
  HoaDonRoute: HoaDonRoute,
  KhachHangRoute: KhachHangRoute,
  KhoHoaDonRoute: KhoHoaDonRoute,
  LoaiChiPhiRoute: LoaiChiPhiRoute,
  MuaHangRoute: MuaHangRoute,
  NhaCungCapRoute: NhaCungCapRoute,
  SanPhamRoute: SanPhamRoute,
  VanChuyenRoute: VanChuyenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
